const createTable = `        
CREATE TABLE IF NOT EXISTS frases_motivacao (
    id SERIAL PRIMARY KEY,
    frase TEXT
);`;

const insertFrase = `
INSERT INTO frases_motivacao (frase) VALUES
    ('A jornada de mil milhas começa com o primeiro passo.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('As dificuldades preparam pessoas comuns para destinos extraordinários.'),
    ('Não tenha medo de falhar, tenha medo de não tentar.'),
    ('A persistência é o caminho do êxito.'),
    ('Você é mais forte do que pensa e mais capaz do que imagina.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Acredite em você mesmo e tudo será possível.'),
    ('Se você acredita que pode, você está no meio do caminho.'),
    ('A vida é 10% do que acontece com você e 90% de como você reage a isso.'),
    ('Grandes sonhos requerem grandes coragens.'),
    ('Tudo que você precisa está dentro de você.'),
    ('Não conte os dias, faça os dias contarem.'),
    ('A disciplina é a ponte entre metas e realizações.'),
    ('Não espere por oportunidades, crie-as.'),
    ('A dor que você sente hoje será a força que você sentirá amanhã.'),
    ('O sucesso não é para os fracos de coração, é para aqueles que têm a coragem de perseverar.'),
    ('Grandes coisas nunca vêm da zona de conforto.'),
    ('A vida é uma aventura ousada ou não é nada.'),
    ('A determinação é o combustível que alimenta a chama do sucesso.'),
    ('O fracasso é apenas uma oportunidade para recomeçar com mais inteligência.'),
    ('Não permita que o medo de perder te impeça de vencer.'),
    ('Você é mais capaz do que imagina.'),
    ('Lembre-se: você é mais forte do que pensa, mais corajoso do que acredita e mais talentoso do que imagina.'),
    ('Não existe um atalho para qualquer lugar que valha a pena chegar.'),
    ('O sucesso é construído sobre a base de fracassos e lições aprendidas.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('A única maneira de fazer um ótimo trabalho é amar o que você faz.'),
    ('A jornada do sucesso começa com um único passo, então dê esse passo corajosamente.'),
    ('O sucesso é uma série de pequenos esforços repetidos dia após dia.'),
    ('Nunca é tarde demais para ser aquilo que você poderia ter sido.'),
    ('Faça algo hoje pelo qual seu "eu" do futuro ficará grato.'),
    ('Não tenha medo de desistir do bom para perseguir o ótimo.'),
    ('A vida é curta demais para se arrepender de não ter tentado.'),
    ('Você não pode mudar seu passado, mas pode moldar seu futuro.'),
    ('O primeiro passo em direção ao sucesso é acreditar que você pode.'),
    ('O sucesso é a soma de pequenos esforços repetidos dia após dia.'),
    ('A motivação é o que te faz começar, o hábito é o que te faz continuar.'),
    ('Grandes coisas nunca vêm de zonas de conforto.'),
    ('Não importa o quão devagar você vá, desde que não pare.');
`;
const getAllFrase = ` SELECT * FROM frases_motivacao order by id;`

const deleteFrase = ` DELETE FROM frases_motivacao WHERE id = $1 RETURNING *; `;

const getFraseByID = `SELECT * FROM frases_motivacao WHERE id = $1 ;`; 

const updateFrase = `UPDATE frases_motivacao SET frase = $1 WHERE id = $2 RETURNING *; `
module.exports = {
    createTable,
    insertFrase,
    getAllFrase,
    getFraseByID,
    deleteFrase,
    updateFrase
}